const Nouns = [
"BEES!",
"strawberrys!",
"misguided advice.",
"anger.",
"entire system of beliefs.",
"my deepest fears.",
"love.",
"money.",
"misery.",
"reality.",
"average.",
"mediocre.",
"meh",
"misery.",
"FREEDOM!",
"subpar activities.",
"trust.",
"negative nancy tendencies.",
"friendship.",
"music.",
"absolute control of the country!",
"quicksand.",
"Africa.",
"Rhode Island.",
"a bizarrely small giraffe.",
"a bizarrely large giraffe.",
"the planet Earth.",
"a remote island in the pacific ocean.",
"a small portion of the Atlantic Ocean.",
"Australia.",
"school.",
"nothing.",
"former president Barack Obama.",
"former vice president Joe Biden",
"the solar system.",
"the new intern.",
"Jesus Christ himself.",
"being tired every dimmadarn day.",
"happiness.",
"dogs. Lot and lots of dogs!"];
