const Nouns = [
"BEES?",
"your misguided advice",
"anger",
"my deepest fears",
"our love",
"your money",
"my misery",
"reality",
"mediocrety",
"FREEDOM!",
"your subpar activities",
"trust",
"the high ground",
"covfefe",
"happines, laughter, and love",
"negative nancy tendencies",
"friendship",
"strawberries",
"music",
"the Alamo",
"quicksand",
"Africa by Toto",
"Rhode Island",
"bizarrely small giraffe",
"planet Earth",
"Djbouti",
"school",
"memes",
"former president Barack Obama",
"former vice president Joe Biden",
"the solar system",
"the new intern",
"Jesus Christ himself",
"being tired every dimmadarn day",
"happiness",
"dogs Lot and lots of dogs!",
"spoopy scary skeletons",
"a warm apple pie on a nice summer day",
"your grandma's old fruit cake",
"creepy mustaches"];
