const Nouns = [
"BEES?",
"misguided advice.",
"anger.",
"my deepest fears.",
"love.",
"money.",
"misery.",
"reality.",
"mediocrety.",
"misery.",
"FREEDOM!",
"subpar activities.",
"trust.",
"the high ground.",
"covfefe",
"happines, laughter, and love.",
"negative nancy tendencies.",
"friendship.",
"music.",
"the Alamo.",
"quicksand.",
"Africa by Toto.",
"Rhode Island.",
"a bizarrely small giraffe.",
"the planet Earth.",
"Djbouti.",
"school.",
"memes",
"former president Barack Obama.",
"former vice president Joe Biden",
"the solar system.",
"the new intern.",
"Jesus Christ himself.",
"being tired every dimmadarn day.",
"happiness.",
"dogs. Lot and lots of dogs!",
"spoopy skeletons",
"a warm apple pie on a nice summer day"
"grandma's old fruit cake",
"creepy mustaches"];
