const Phrases = [
"Hope your day is filled with <noun>.",
"Hope your day is just like <noun>.",
"Without you, I wouldn't have <noun>.",
"I love you as much as I love <noun>.",
"I was so excited about your birthday I forgot to bring <noun>.",
"Thank you for the greatest gift of all, <noun>.",
"I can't imagine life without <noun>.",
"You make me see the good in this world, like <noun>.",
"Life without you is like a world without <noun>.",
"For this special day I bought you <noun>.",
"If I could give you one piece of advice, it would be: Remember <noun>.",
"It's over Anakin. I have <noun>.",
"I love you for so many reasons, especially <noun>.",
"Through this and thin I can always rely on your love for <noun>.",
"You remind me to always be thankful for <noun>.",
"I wrote you a love song, I call it <noun>.",
"If you and I had a love song, it would be called <noun>.",
"To a special friend, who always brought me <noun>.",
"You've always brought the greatest gift of all to my life: <noun>.",
"You were the one who finally made me understand <noun>.",
"I always thought you were lame until you showed me <noun>.",
"This place sucked until you came along, well you and <noun>.",
"I've got 99 problem but thanks to you, <noun> ain't one.",
"You've shown me how much a person can love <noun>.",
"You've always been able to cheer me up, especially with <noun>.",
"Thank you so much for <noun>.",
"Simply... <noun>.",
"You showed me the true meaning of <noun>.",
"Shh... don't say anything, I understand everything now, even <noun>.",
"Without you, I would have no idea how to deal with <noun>.",
"We could be happy ever after... Just you, me, and <noun>.",
"You've always been my favorite I superhero, well... next to <noun>.",
"I wrote you a love song, I call it <noun>.",
"If you and I had a love song, it would be called <noun>.",
"To a special friend, who always brought me <noun>."];
